services:
  app:
    image: node:22-alpine
    container_name: my-nest-dev
    working_dir: /app
    ports:
      - "80:3000"
    volumes:
      - /home/ubuntu/appbase/app:/app
      - /home/ubuntu/appbase/node_readonly_modules:/app/node_modules
    command: >
      sh -c "
      apk add --no-cache libc6-compat &&
      corepack enable pnpm &&
      pnpm install &&
      pnpm build &&
      npm install -g pm2 &&
      pm2-runtime start ecosystem.config.js
      "
