name: master_deploy_docker

on:
  push:
    branches:
      - master     

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      # Step1. Source CheckOut ( v3 )
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step2-A. Docker Build Setup  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step2-B. Docker Hub Login 
      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step2-C. Docker Image Push     
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: latest

      # Step3. Run remote shell using ssh 
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo " ========== START of Deployment v1.1 ==========="
            sudo docker compose down 
            sleep 1
            sudo docker compose up -d 
            ls -al >> "Deployment_At_$(date '+%Y%m%d_%H:%M:%S').log"
