name: master_deploy_docker

on:
  push:
    branches:
      - master     

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      # Step1. Source CheckOut ( v3 )
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step2-A. Docker Multi-Arch Docker Image
      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v3

      # Step2-B. Docker Build Setup  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step2-C. Docker Hub Login 
      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step2-D. Docker Image Push     
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:latest

      # Step3. Create .env.production file on runner
      - name: Create .env.production file on runner  
        run: |
          echo "${{ secrets.PROD_ENV_CONTENT }}" > .env.production

      # Step4. Run remote shell using ssh 
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: ".env.production" # File by Actions Runner 
          target: "${{ secrets.DOCKER_COMPOSE_ROOT }}/.env.production" # .absolute path on remote server          
          script: |
            echo " ========== START of Deployment ==========="
            cd ${{ secrets.DOCKER_COMPOSE_ROOT }}  
            sudo docker compose down 
            sleep 1
            sudo docker rmi -f ${{ secrets.DOCKER_REPOSITORY }}:latest || true:  
            sleep 1
            sudo docker compose up -d 
            
