name: master_remote_work

on:
  push:
    branches:
      - master     

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
 
      - name: Deploy
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        run: |
          echo "S3_BUCKETNAME : ${{ secrets.SERVER_USERNAME }}"
          echo "REMOTE_SSH_KEY : ${{ secrets.REMOTE_SSH_KEY }}"
  